# Generated by Django 3.1.13 on 2021-07-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmittedPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitDate', models.DateField(auto_now=True)),
                ('patient_admitted', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
