# Generated by Django 3.1.13 on 2021-07-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctor'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time', models.BooleanField(default=True, verbose_name='Is it a first time appointment or not?')),
                ('appointment_date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('doctor_assigned', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointed', to='users.doctor')),
                ('nurse_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_assigned', to='users.nurse')),
                ('patient_appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
