# Generated by Django 3.1.13 on 2021-07-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctor'),
        ('appointments', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('condition', models.CharField(choices=[('Normal', 'Normal'), ('Stable', 'Stable'), ('Critical', 'Critical'), ('Pending', 'Pending')], default='Normal', max_length=20, verbose_name='Patient Status/Condition')),
                ('patient_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
