# Generated by Django 3.1.13 on 2021-07-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctor'),
        ('appointments', '0003_patientstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Medication name')),
                ('dose', models.CharField(max_length=50, verbose_name='Dosage')),
                ('extra_info', models.CharField(max_length=250, verbose_name='Additional Information')),
                ('side_effect', models.CharField(max_length=1000, verbose_name='Any side effects')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescription', to='users.doctor', verbose_name='Doctor Prescribing the drug')),
                ('drugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to='appointments.drugs', verbose_name='Drug prescriptions')),
                ('patient_prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescription', to='users.patient')),
            ],
        ),
    ]
